name: Main branch updated
on:
  push:
    branches:
      - main
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - name: Install devDependencies
        run:  NODE_ENV=development npm ci
      - name: Run ESLint
        run:  npm run validate:lint
      - name: Run unit tests
        run: npm run validate:test
      - name: Check test coverage
        run:  npm run validate:coverage
  build:
    name: Build
    runs-on: ubuntu-latest
  test:
    name: Test
    runs-on: ubuntu-latest
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
