name: Lint/Test/Code Coverage
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - name: Install devDependencies
        run:  NODE_ENV=development npm ci
      - name: Run ESLint
        run:  npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - name: Install devDependencies
        run:  NODE_ENV=development npm ci
      - name: Run test and check coverage
        run:  npm run coverage
